### PR TITLE
Create library.json

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
here's a few more libs in need of library.json

https://github.com/PaulStoffregen/ILI9341_t3
https://github.com/PaulStoffregen/XPT2046_Touchscreen
https://github.com/PaulStoffregen/ILI9341_fonts

**Comment by ivankravets** [comment]
Thanks @PaulStoffregen, I'll add them. I need this lib for Audio library as dependency. I'll propose you the one interesting PR for Audio library within a few minutes. You feedback is valuable for me.

**Comment by PaulStoffregen** [comment]
Have you used this audio lib on a Teensy3 yet?

If not, this video can give you a good idea of what it can do....

https://www.youtube.com/watch?v=wqt55OAabVs

You might also want to look at how the design tool might integrate with platformio....

**Comment by ivankravets** [comment]
I saw this video (I follow you :) ). Excellent workshop!!! I've not tried it yet. However, it looks amazing!

What do you think about this? https://github.com/PaulStoffregen/Audio/pull/135

**Pull request merged**
